### ISSUE TITLE
Mod Mountain Support

### ISSUE THREAD

**Issue by sirsavary** [SecureGMod/public-issue-list#5]
It's important that a product such as SecureGMod does not continue to enable and encourage the current monopoly within the paid addon community. Support for competitors, such as Mod Mountain, is paramount and should be included before the official launch.

**Comment by colemclaren** [comment]
![https://moat.la/i/j/KImWh](https://moat.la/i/j/KImWh)

**Comment by sirsavary** [comment]
Delete This

**Comment by Caiiin** [comment]
no u

**Comment by meepen** [comment]
make modmountain 👌

**Comment by sirsavary** [comment]
You will be hearing from our legal team

**Comment by KabusDev** [comment]
did your legal team also get you permission to use copyrighted music from a game on your upcomming marketplace website
